add jmespath to requirements
oVirt/ovirt-ansible-vm-infra pull request #122
Opened 2020-01-28 08:10 UTC by mnecas

Fixes https://github.com/oVirt/ovirt-ansible-image-template/issues/63
@mwperina

2020-01-28 08:15 UTC, mnecas commented
ci build please

2020-01-29 09:13 UTC, mwperina requested changes

2020-01-29 09:13 UTC, mwperina commented on README.md
> + * python3-jmespath
Isn't it worth to mention also python2 variant?

2020-01-29 09:13 UTC, mwperina commented on ovirt-ansible-vm-infra.spec.in
> +Requires: ansible >= 2.9.0, python3-jmespath
Please put python3-jmespath on separate line and IMO it's worth also to split it to support also EL7:

```
%if 0%{?rhel} <= 7
Requires	python-jmespath
%else
Requires	python3-jmespath
%endif
```

2020-04-07 13:23 UTC, mwperina approved these changes
+1

2020-04-07 13:46 UTC, merged