Add files via upload
oVirt/ovirt-ansible-vm-infra pull request #15
Opened 2018-03-15 16:08 UTC by stvnrsnbrg

Adding an ansible affinity group example to the ansible project.

2018-03-15 16:08 UTC, ovirt-infra commented
Hello contributor, thanks for submitting a PR for this project! 

I am the bot who triggers "standard-CI" builds for this project.
As a security measure, I will not run automated tests on PRs that are not from white-listed contributors.

In order to allow automated tests to run, please ask one of the project maintainers to review the code and then do one of the following:

1. Type `ci test please` on this PR to trigger automated tests for it.
2. Type `ci add to whitelist` on this PR to trigger automated tests for it and also add you to the contributor white-list so that your future PRs will be tested automatically.
3. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the project organization, so you'll be able to run tests for all the organization's projects.

2018-03-15 20:00 UTC, mykaul commented
Nice. I wonder how common it is to provide documentation within the playbook.
Perhaps the vars should be in a separate file?

2018-03-16 08:53 UTC, machacekondra commented
@mykaul I think it should be in `examples` directory as it currently is. We ship this directory with RPM in `/usr/share/doc/{packagename}/examples`. It will be shipped also from galaxy as whole git repo is installed.

2018-03-16 08:54 UTC, machacekondra commented
@MarSik

2018-03-16 13:26 UTC, MarSik commented
It should get some documentation at the top even in examples. Just to make sure users understand what the example is doing.

Btw, I believe a single strong negative affinity group A-B should be enough to achieve what Yaniv wanted as it actually does not matter where the two VMs are running as long as they are not on the same host.

2018-03-16 13:28 UTC, MarSik commented
And one other note.. Ondra should probably tell us whether the role creates the VMs and adds the hosts too or whether it uses the vars just as references.

2018-03-16 15:14 UTC, machacekondra commented
It doesn't create the hosts, it only creates a VMs.

2018-03-16 15:23 UTC, MarSik commented
I am not sure that is desirable in this case.. it might be, but the example must then mention that it creates both VMs and the affinity that makes them suitable for HA load

2018-03-18 07:36 UTC, mykaul commented
@machacekondra - I actually did not want this as an example, but as a reusable role others can use.
For example, OpenShift installation (https://github.com/openshift/openshift-ansible-contrib/blob/master/reference-architecture/rhv-ansible/playbooks/vars/ovirt-infra-vars.yaml#L116 ) might be able to use this on a hyper-converged specific infra., etc.

2018-03-19 11:13 UTC, MarSik commented
@mykaul Is there a reason you wanted to limit where the VMs are allowed to run instead of just making sure they never run together?

2018-03-19 11:38 UTC, mykaul commented
@MarSik - no reason to limit - just a simple use case - RHHI (hyper-converged). I feel a simple role that can be extended is better than an abstract one.

2018-03-20 07:01 UTC, machacekondra commented
@mykaul Well, that role you want is this role, actually. So is this missing some features? I think I still don't understand what is needed here.

2018-03-20 09:36 UTC, mykaul commented
How can people re-use it? Perhaps I wasn't clear - I do not want people to
re-write this piece of code over and over, but re-use this simple playbook
- perhaps it should be a task?
Given 2 VMs and 3 hosts, create anti-affinity between the VMs and
soft-affinity between the hosts and the VMs properly (as was done in this
PR).

I think it's useful to any given HA VMs pair.

On Tue, Mar 20, 2018 at 9:01 AM, Ondra Machacek <notifications@github.com>
wrote:

> @mykaul <https://github.com/mykaul> Well, that role you want is this
> role, actually. So is this missing some features? I think I still don't
> understand what is needed here.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/oVirt/ovirt-ansible-vm-infra/pull/15#issuecomment-374495853>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AEcJ6UcXJShQnF-gC3SZtxoWTIc0eAdFks5tgKlFgaJpZM4SscG4>
> .
>

2018-03-29 13:38 UTC, machacekondra commented
In that case having such example is the best what we can have I think. I will review and merge.

2018-03-29 13:39 UTC, machacekondra commented on examples/ovirt_affinity_infra.yml
> +    engine_url: http://localhost:8080/ovirt-engine/api
We use this in all examples:
```
engine_url: //ovirt-engine.example.com/ovirt-engine/api
```

2018-03-29 13:39 UTC, machacekondra commented on examples/ovirt_affinity_infra.yml
> +    # engine_cafile: /etc/pki/ovirt-engine/ca.pem
Please uncomment.

2018-03-29 13:40 UTC, machacekondra commented on examples/ovirt_affinity_infra.yml
> +    hosts:
Please remove, we don't add any hosts by this role.

2018-03-29 13:40 UTC, machacekondra commented on examples/ovirt_affinity_infra.yml
> +    phys_host:
Please remove.

2018-03-29 13:41 UTC, machacekondra commented on examples/ovirt_affinity_infra.yml
> +      cluster: Default
I would add also a `template` for the profile. For example:
```yaml
dist_vm:
  cluster: Default
  template: rhel74
```

2018-03-29 13:42 UTC, machacekondra requested changes
Looks OK in general, few comments.

2018-03-31 06:26 UTC, MarSik commented
@mykaul But there is no reason to limit the VMs more than by anti-affinity between them. So the question is whether this is supposed to be a production best practices example or an artificial feature showcase.

2018-08-14 13:39 UTC, machacekondra commented
Please re-open if still valid.

2018-08-14 13:39 UTC, closed without merging