Support new default galaxy name
oVirt/ovirt-ansible-vm-infra pull request #57
Opened 2018-11-06 12:23 UTC by machacekondra

This patch add RPM support for ovirt.vm-infra name, as is default now in galaxy and add note about it in README.doc.

Change-Id: Ia38ae8cd986b4421a4b127d7f37eabe0ee6782d8
Signed-off-by: Ondra Machacek <omachace@redhat.com>

2018-11-06 12:26 UTC, machacekondra commented
@mwperina @pkubica

2018-11-06 12:30 UTC, machacekondra commented
ci build please

2018-11-06 12:30 UTC, machacekondra commented
After this patch RPM installs following:

```bash
$ ll /usr/share/ansible/roles/
lrwxrwxrwx. 1 root     root       39 Nov  6 13:03 ovirt-vm-infra -> /usr/share/ansible/roles/ovirt.vm-infra
drwxr-xr-x. 6 root     root     4096 Nov  6 13:29 ovirt.vm-infra
lrwxrwxrwx. 1 root     root       39 Nov  6 13:03 oVirt.vm-infra -> /usr/share/ansible/roles/ovirt.vm-infra
```

2018-11-06 14:25 UTC, mwperina requested changes

2018-11-06 14:25 UTC, mwperina commented on README.md
> +`OVIRT.vm-infra`, so you later always have to use this role with upper case prefix. So be carefull how
careful

2018-11-06 14:25 UTC, mwperina commented on README.md
> +So you can use any of this name. This documentation and examples in this repository are using name `ovirt.vm-infra`.
We should mention that oVirt.vm-infra and ovirt-vm-infra are deprecated

2018-11-06 14:26 UTC, mwperina commented
Other than that it looks good!

2018-11-06 15:32 UTC, machacekondra commented on README.md
> +`OVIRT.vm-infra`, so you later always have to use this role with upper case prefix. So be carefull how
Changed

2018-11-06 15:32 UTC, machacekondra commented on README.md
> +So you can use any of this name. This documentation and examples in this repository are using name `ovirt.vm-infra`.
Added.

2018-11-07 09:45 UTC, mwperina requested changes

2018-11-07 09:45 UTC, mwperina commented on README.md
> +Please note that when installaling this role from Ansible Galaxy you are instructed to run following command:
installing

2018-11-07 09:45 UTC, mwperina commented on README.md
> +This will download the role to the directory with same name as you specified on the
... the same name ...

2018-11-07 09:45 UTC, mwperina commented on README.md
> +`oVirt.vm-infra` and `ovirt-vm-infra` are deprecated.
`oVirt.vm-infra` and `ovirt-vm-infra` role names are deprecated.

2018-11-16 10:09 UTC, mwperina approved these changes

2018-11-16 10:14 UTC, merged